In [1]:
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans
from collections import Counter
import os

# Caminho para a Silver (saída do write_silver.py)
silver_path = "../../data/silver/cision_news_20251110.parquet"

if not os.path.exists(silver_path):
    raise FileNotFoundError(f" Ficheiro Silver não encontrado em {silver_path}")

df = pd.read_parquet(silver_path)
print(f"1Silver carregada com {len(df)} notícias únicas")
df.head(3)

c:\Users\inesc\Downloads\ISCTE\Planapp\Planapp\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

1Silver carregada com 43665 notícias únicas

,id,titulo,noticia_raw,noticia_norm,link,data_publicacao,tipo_meio,autores,valor_publicitario,guid,categoria,grupo_id,is_lider,processed_at
0,116477697,Isabel Ferreira reafirma compromisso com Braga...,A candidata à Presidência da Câmara Municipal ...,a candidata à presidência da câmara municipal ...,No link available,2025-04-03 00:00:00+00:00,Imprensa,sem autor,139.4,http://pt.cision.com/cp2013/clippingdetails.as...,None,0,True,2025-11-10T15:53:56Z
1,116477659,Legislativas 25 - Júlia Rodrigues escolhida pa...,"A presidente da Câmara de Mirandela, Júlia Rod...",a presidente da câmara de mirandela júlia rodr...,No link available,2025-04-03 00:00:00+00:00,Imprensa,"Fernando Pires, António Gonçalves Rodrigues",267.2,http://pt.cision.com/cp2013/clippingdetails.as...,None,1,True,2025-11-10T15:53:56Z
2,116456100,Alargamento dos passeios na envolvente à Casa-...,"Arrancou na passada segunda-feira, o alargamen...",arrancou na passada segunda feira o alargament...,No link available,2025-04-02 00:00:00+00:00,Imprensa,sem autor,100.0,http://pt.cision.com/cp2013/clippingdetails.as...,None,2,True,2025-11-10T15:53:56Z

In [2]:
from sentence_transformers import SentenceTransformer
import time

# Criar amostra 10%
df_sample = df.sample(frac=0.10, random_state=42).reset_index(drop=True)

print(f"Amostra com {len(df_sample)} notícias")

# Carregar modelo
model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

# Gerar embeddings
start = time.time()
embeddings = model.encode(
    df_sample["noticia_norm"].astype(str).tolist(),
    batch_size=16,
    show_progress_bar=True,
    normalize_embeddings=True
)
print(f"Embeddings criados: {embeddings.shape}")
print(f"Tempo total: {(time.time()-start)/60:.1f} minutos")

Amostra com 4366 notícias

Batches: 100%|██████████| 273/273 [02:31<00:00,  1.80it/s]

Embeddings criados: (4366, 384)
Tempo total: 2.5 minutos

In [6]:
import umap

umap_reducer = umap.UMAP(n_components=10, random_state=42)
embeddings_reduced = umap_reducer.fit_transform(embeddings)

print(f"Dimensão original: {embeddings.shape[1]} → Reduzida: {embeddings_reduced.shape[1]}")

c:\Users\inesc\Downloads\ISCTE\Planapp\Planapp\.venv\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Dimensão original: 384 → Reduzida: 10

In [7]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

Ks = [16, 18, 22]
scores = []

for k in Ks:
    labels = KMeans(n_clusters=k, random_state=42).fit_predict(embeddings_reduced)
    score = silhouette_score(embeddings_reduced, labels)
    print(f"k={k}: Silhouette={score:.3f}")
    scores.append((k, score))

best_k, best_score = max(scores, key=lambda x:x[1])
print(f"\nMelhor k = {best_k}, Silhouette = {best_score:.3f}")

df_sample["cluster_id"] = KMeans(n_clusters=best_k, random_state=42).fit_predict(embeddings_reduced)

k=16: Silhouette=0.355
k=18: Silhouette=0.333
k=22: Silhouette=0.332

Melhor k = 16, Silhouette = 0.355

In [8]:
from sklearn.cluster import KMeans
from collections import Counter
import nltk
from nltk.corpus import stopwords

k_escolhido = 18 

# Treinar K-Means final
kmeans_final = KMeans(n_clusters=k_escolhido, random_state=42, n_init=10)
df_sample["cluster_id"] = kmeans_final.fit_predict(embeddings_reduced)

# Preparar stopwords PT
nltk.download('stopwords')
stop_words = set(stopwords.words("portuguese"))

print("\nPalavras mais comuns por cluster:")

for c in sorted(df_sample["cluster_id"].unique()):
    palavras = " ".join(df_sample[df_sample.cluster_id == c]["noticia_norm"])
    tokens = [p for p in palavras.split() if p not in stop_words and len(p) > 3]
    mais_comuns = Counter(tokens).most_common(15)

    print(f"\nCluster {c}:")
    print(", ".join([p[0] for p in mais_comuns]))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\inesc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Palavras mais comuns por cluster:

Cluster 0:
governo, presidente, república, sobre, ministro, assembleia, estado, ainda, regional, euros, primeiro, portugal, chega, madeira, municipal

Cluster 1:
euros, saúde, social, investimento, milhões, câmara, escola, presidente, projeto, centro, municipal, ainda, obra, plano, apoio

Cluster 2:
saúde, médicos, cuidados, hospital, profissionais, serviço, anos, ainda, trabalho, médico, nacional, medicina, presidente, pessoas, sobre

Cluster 3:
europeia, comissão, sobre, europeu, união, presidente, europa, milhões, euros, estados, ainda, política, trump, tarifas, portugal

Cluster 4:
habitação, câmara, construção, euros, municipal, casas, governo, ainda, anos, presidente, milhões, investimento, habitações, concelho, reabilitação

Cluster 5:
empresas, inovação, digital, indústria, formação, trabalho, portugal, setor, ensino, emprego, anos, desenvolvimento, ainda, mercado, euros

Cluster 6:
câmara, euros, obra, construção, municipal, presidente, investimento, linha, milhões, ainda, obras, empreitada, intervenção, nova, execução

Cluster 7:
câmara, municipal, concelho, presidente, assembleia, anos, candidato, ainda, lista, pessoas, todos, habitação, trabalho, porque, fazer

Cluster 8:
chega, governo, presidente, sobre, república, pedro, partido, montenegro, luís, política, ainda, ventura, líder, porque, direita

Cluster 9:
euros, câmara, municipal, obra, presidente, espaço, obras, milhões, investimento, projeto, município, concurso, requalificação, ainda, parque

Cluster 10:
trabalho, trabalhadores, governo, desemprego, emprego, ainda, pessoas, anos, número, euros, segundo, portugal, empresas, greve, sobre

Cluster 11:
partido, eleições, chega, votos, anos, assembleia, ainda, legislativas, câmara, eleitoral, municipal, deputados, república, presidente, todos

Cluster 12:
governo, orçamento, estado, euros, proposta, milhões, 2026, sobre, ministro, finanças, chega, ainda, república, feira, presidente

Cluster 13:
presidente, portugal, francisco, estado, república, lisboa, anos, governo, sobre, papa, ainda, incêndios, ministro, primeiro, nacional

Cluster 14:
anos, presidente, ainda, municipal, câmara, concelho, todos, feira, centro, portugal, pessoas, cultural, onde, nova, espaço

Cluster 15:
euros, milhões, produção, portugal, ainda, energia, projeto, água, nacional, governo, investimento, setor, anos, empresas, desenvolvimento

Cluster 16:
governo, portugal, chega, nacionalidade, estrangeiros, estado, ministro, país, sobre, república, ainda, anos, presidente, imigrantes, pessoas

Cluster 17:
portugal, milhões, euros, empresas, ainda, governo, economia, crescimento, investimento, sobre, 2024, europeia, país, maior, anos

In [ ]:
# TF-IDF para extrair termos importantes por cluster

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

print("\n🔍 A calcular TF-IDF por cluster...\n")

# stopwords tem de ser LISTA para o TF-IDF
stop_words = list(stopwords.words("portuguese"))

vectorizer = TfidfVectorizer(
    max_features=3000,
    stop_words=stop_words,
    ngram_range=(1,2)   # inclui bigramas
)

for c in sorted(df_sample["cluster_id"].unique()):
    textos = df_sample[df_sample.cluster_id == c]["noticia_norm"].tolist()

    if len(textos) < 3:
        print(f"\nCluster {c}: (poucos textos)")
        continue

    # TF-IDF para o cluster
    tfidf_matrix = vectorizer.fit_transform(textos)
    scores = tfidf_matrix.mean(axis=0).A1
    termos = vectorizer.get_feature_names_out()

    # top termos
    top_idx = scores.argsort()[::-1][:15]
    top_termos = [termos[i] for i in top_idx]

    print(f"\n Cluster {c} — termos TF-IDF mais relevantes:")
    print(", ".join(top_termos))

🔍 A calcular TF-IDF por cluster...


 Cluster 0 — termos TF-IDF mais relevantes:
governo, ministro, ps, presidente, luís, chega, república, declarações, primeiro, parlamento, estado, josé, sobre, primeiro ministro, vai

 Cluster 1 — termos TF-IDF mais relevantes:
saúde, euros, social, escola, investimento, milhões, câmara, centro, projeto, obra, unidade, vai, presidente, ano, alunos

 Cluster 2 — termos TF-IDF mais relevantes:
saúde, médicos, hospital, sns, ministra, serviço, profissionais, presidente, ordem, médico, cuidados, nacional, enfermeiros, declarações, martins

 Cluster 3 — termos TF-IDF mais relevantes:
europeia, comissão, presidente, trump, comissão europeia, tarifas, europeu, união, sobre, ue, estados, milhões, união europeia, europa, euros

 Cluster 4 — termos TF-IDF mais relevantes:
habitação, câmara, euros, construção, municipal, casas, governo, milhões, habitações, reabilitação, arrendamento, fogos, milhões euros, mil, investimento

 Cluster 5 — termos TF-IDF mais relevantes:
empresas, emprego, digital, formação, indústria, inovação, portugal, trabalho, profissional, ensino, euros, setor, mercado, milhões, empresa

 Cluster 6 — termos TF-IDF mais relevantes:
câmara, obra, euros, municipal, porto, obras, rua, construção, empreitada, investimento, intervenção, presidente, execução, milhões, nova

 Cluster 7 — termos TF-IDF mais relevantes:
psd, câmara, presidente, municipal, assembleia, candidato, ps, concelho, lista, pedro, partido, anos, porto, cdu, candidatura

 Cluster 8 — termos TF-IDF mais relevantes:
ps, chega, luís, república, pedro, presidente, ventura, montenegro, declarações, andré, andré ventura, governo, luís montenegro, sobre, psd

 Cluster 9 — termos TF-IDF mais relevantes:
euros, câmara, municipal, obra, espaço, concurso, obras, parque, milhões, mil, requalificação, presidente, projeto, mil euros, investimento

 Cluster 10 — termos TF-IDF mais relevantes:
trabalhadores, trabalho, desemprego, governo, ano, mês, emprego, taxa, greve, pessoas, segundo, euros, portugal, mil, taxa desemprego

 Cluster 11 — termos TF-IDF mais relevantes:
partido, ps, eleições, chega, ad, votos, psd, campanha, voto, presidente, distrito, deputados, assembleia, república, esquerda

 Cluster 12 — termos TF-IDF mais relevantes:
governo, orçamento, estado, orçamento estado, ministro, euros, proposta, ano, ps, parlamento, 2026, milhões, república, irs, luís

 Cluster 13 — termos TF-IDF mais relevantes:
análise, presidente, incêndios, portugal, república, francisco, bombeiros, ministro, governo, declarações, sousa, estado, anos, abril, assembleia

 Cluster 14 — termos TF-IDF mais relevantes:
anos, dia, municipal, presidente, ano, ainda, câmara, concelho, portugal, feira, centro, freguesia, município, vila, espaço

 Cluster 15 — termos TF-IDF mais relevantes:
euros, milhões, milhões euros, energia, regional, portugal, projeto, programa, governo, água, energética, produção, investimento, madeira, ainda

 Cluster 16 — termos TF-IDF mais relevantes:
lei, governo, chega, portugal, ministro, nacionalidade, estrangeiros, república, presidente, ps, tribunal, declarações, parlamento, imigrantes, luís

 Cluster 17 — termos TF-IDF mais relevantes:
milhões, euros, portugal, milhões euros, empresas, economia, ano, governo, mil, prr, banco, crescimento, europeia, mil milhões, ainda

In [33]:
print("------ CLUSTER 0 ------")
print("\n".join(df_sample[df_sample.cluster_id == 0]["noticia_norm"].head(10)))

print("\n------ CLUSTER 3 ------")
print("\n".join(df_sample[df_sample.cluster_id == 3]["noticia_norm"].head(10)))

------ CLUSTER 0 ------
rui rocha despediu se da liderança da il na convenção em alcobaça com recados para dentro e fora admitiu que não foram cumpridos os objetivos e apelou ao partido para olhar para o futuro no arranque da x convenção da iniciativa liberal il rui rocha subiu ao palco para um discurso enquanto presidente cessante e aquilo que seria um balanço do seu mandato revelou se um claro ajuste de contas com muitas farpas aos críticos à mistura e recados para a sucessora o ex líder dos liberais garantiu estar de consciência tranquila e deixa o cargo com o mesmo desprendimento dos seus antecessores sublinhando que em dois anos e meio a il passou a estar presente em todos os parlamentos e tem uma visão estratégica e autonomia política e financeira para o futuro cabe a mariana leitão provar agora que o partido vale mais do que 5% dos votos houve vozes revelantes na ll que comentaram resultados mas a decisão foi minha e essas vozes foram absolutamente irrelevantes na minha tomada de decisão assegurou rocha no multiusos de alcobaça numa alusão a bernardo blanco e cotrim figueiredo que defenderam que o resultado das legislativas ficou aquém do esperado e a il devia ter mais ambição ainda assim reconheceu que não foram cumpridos os objetivos com a il a não conseguir reforçar a influência da il na governação apesar de ter alcançado em maio o melhor resultado em legislativas depois de três eleições a 5% só há duas possibilidades ou o teto é do partido ou o teto é do presidente só há uma maneira de sabermos é o presidente dar um passo ao lado argumentou a bola está agora do lado de mariana leitão a quem desafia provar que a il consegue atingir outro patamar eleitoral tenho a certeza que quem vem atrás de mim melhor fará atirou olhando para os ex presidentes do partido notou que nenhum deles cumpriu mais do que um mandato por razões diferentes mas criticou o sebastianismo referindo se aqueles que insistem no regresso de carlos guimarâes pinto ou joão cotrim de figueiredo para a presidência da il vamos para a frente vamos embora cuidado com o regresso ao passado vamos olhar para para futuro advertiu críticas ao sebastianismo prometeu ainda dar o seu contributo para o combate ao sebastianismo garantindo não ter disponibilidade para qualquer tipo de função em órgãos de partido a menos que aconteça uma desgraça o que manifestamente nem prevejo nem desejo afiançou contra o rótulo da moderação disse que nunca foi moderado na defesa do partido e dos valores do liberalismo considerando que arriscou por exemplo não ser eleito para o parlamento ao ser cabeça de lista por braga e teve coragem também ao não aceitar uma coligação pré eleitoral com a ad tive coragem quando recusei coligações pré eleitorais e quando recusei ir para o governo porque não troco ideias por cargos podíamos ter 10 20 ou 30 deputados para no dia seguinte estar a privatizar a tap a 49% não pode ser não era para isso que cá estavamos atirou defendendo a privatização total da companhia aérea e atirou se à ad ao ps e chega afirmando que se antónio costa ou pedro nuno santos eram as caras do negócio ruinoso da tap hoje são luís montenegro josé luís carneiro e andré ventura que querem manter tudo igual defesa da liberdade de expressão na ar despindo o fato de presidente cessante e assumindo a voz de deputado rocha aproveitou ainda a sua intervenção para sair em defesa da absoluta liberdade de expressão no parlamento afirmando que quer josé luís carneiro quer andré ventura têm o direito de usar as expressões fanfarrão e frouxo o grau de filigrana que estamos a construir para chegar a uma conclusão que devia ser a primeira liberdade de expressão a liberdade é de cada um que usa e como usa quando de um lado se diz que uns são fanfarrões e que do outro lado são frouxos ambos têm razão concluiu a reunião magna dos liberais elegerá este sábado mariana leitão como a nova líder da il a sua direção e moção de estratégia global para os próximos dois anos liliana coelho jornalista liliana coelho
crossfire com miguel relvas pedro adão e silva e rui moreira
comentário de henrique monteiro temas nova declaração de interesses do pm debates para as legislativas
secretário geral do pcp defende que se apresentem propostas para melhorar a vida das pessoas o secretário geral do pcp criticou este domingo a troca de galhardetes entre líderes partidários e sublinhou que a campanha deveria focar se por outro lado na discussão de temas essenciais e propostas para melhorar a vida dos portugueses não precisamos de fazer trocas de galhardetes precisamos é de apresentar propostas para melhorar a vida das pessoas salários direitos fim da precariedade respeito pelos horários defendeu paulo raimundo o líder da cdu pcp e partido ecologista os verdes pev respondia aos jornalistas no final de uma marcha que terminou com um comício nos bombeiros mistos do seixal dedicado ao trabalho questionado sobre as declarações pedro nuno santos que recordou a governação de passos coelho para deixar criticas à ad paulo raimundo disse estranhar a comparação do líder do ps partido que no ano passado viabilizou o orçamento do estado do governo de luís montenegro sem se alongar nos comentários paulo raimundo disse apenas que são galhardetes soundbites e frases feitas e que da sua parte prefere centrar se nas propostas que a coligação apresenta para as eleições legislativas de 18 de maio desde logo a melhoria das condições de trabalho tema que esteve em destaque no comício realizado durante a tarde no seixal autarquia comunista e em que estiveram presentes algumas centenas de militantes e apoiantes da cdu se a força do trabalho se impuser a vida do país anda para a frente a vida da maioria anda para a frente exclamou perante um auditório cheio nas eleições passadas a cdu elegeu um deputado pelo distrito de setúbal paula santos líder parlamentar do pcp questionado à entrada pelos jornalistas se as várias iniciativas agendadas para o distrito durante as duas semanas de campanha refletem o receio de perder essa representação a partir de 18 de maio paulo raimundo riu se estamos empenhadíssimos em reforçar e precisamos que no distrito de setúbal a paula santos o bruno dias e a heloísa apolónia candidata do pev voltem à assembleia estamos empenhados em crescer e avançar justificou o líder comunista escusou se também a comentar aritméticas e contas para possíveis cenários resultantes das eleições defendendo que a única maneira de reforçar a esquerda no parlamento para forçar caminhos de esquerda é dando força à cdu esta é uma condição essencial afirmou sem responder se o partido está disponível para uma reedição da geringonça lusa
pedro santana lopes protagonista now traz nos a sua crónica semanal que engloba e explora as mais diversas referências da atualidade política nacional e internacional com especial destaque hoje para presidenciais antónio filipe é candidato a belém seguro é o grande candidato da esquerda ps pode tornar se ainda mais irrelevante não acredito que santos silva desista paulo portas ainda não se retirou de cena educação telemóveis proibidos nas escolas julgamento anjos vs joana marques irmãos rosado exigem mais de um milhão defesa dos anjos contesta depoimento operação marquês josé sócrates apresenta queixa contra o estado lua nova parlamento de espanha quarto minguante andré villas boas quarto crescente josé luís carneiro lua cheia normalização institucional da assembleia da república música da semana stuck with u ariana grande e justin bieber

In [38]:
print("\n------ CLUSTER 1 ------")
print("\n".join(df_sample[df_sample.cluster_id == 1]["noticia_norm"].head(10)))

print("\n------ CLUSTER 2 ------")
print("\n".join(df_sample[df_sample.cluster_id == 2]["noticia_norm"].head(10)))

------ CLUSTER 1 ------
a casa dos crivos situada na rua de s marcos em braga vai entrar em obras de reabilitação e restauro no próximo mês de julho a notícia foi confirmada pelo presidente da câmara de braga que realçou estar tudo praticamente pronto para que os trabalhos avancem «já tinha sido lançado o concurso tinham sido cumpridas todas as formalidades administrativas necessárias e neste momento já estão em curso os preparativos para o arranque da obra que vai de facto iniciar se no início do mês de julho» disse ricardo rio ao diário do minho ainda segundo o autarca o concurso aponta para que as obras decorram num prazo de 150 dias ou seja cinco meses pelo que tudo deverá estar concluído no próximo mês de de zembro o valor orçamentado para os trabalhos é de cerca de 400 mil euros «são várias as intervenções que vão ser feitas quer do ponto de vista da salvaguarda patrimonial quer também da melhoria das condições de funcionalidade do espaço e portanto eu diria que até ao fni al do ano até ao mês de dezembro teremos a intervenção completamente concluída» acrescentou o presidente da câmara de braga segundo o planeado a intervenção contempla o restauro dos elementos originais do edifício a re solução dos problemas de infiltração que se têm registado nos espaços interiores do edifício os quais inviabilizam a utilização do edifício a melhoria da envolvente exterior para otimizar seu desempenho térmico a dotação de infraestruturas que potenciem a funcionalidade utilização e dinâmica do equipamento cultural e a melhoria das condições das acessibilidades para pessoas com mobilidade reduzida ou condicionada assim no exterior a intervenção vai substituir as coberturas em telha cerâmica com colocação de telas impermeabilizantes e isolamento térmico substituit os elementos do sistema de drenagem de águas pluviais nomeadamente rufos caleiros e tubos de queda restaurar os elementos originais do edifício nomeadamente a fachada em gelosia e as respetivas portadas de madeira que se sucedem reabilitar a fachada posterior incluindo terraço e muros e substituir as caixilharias exteriores em madeira da fachada posterior trabalhos intervenção a realizar no interior da casa dos crivos no interior a intervenção contempla a demolição remoção de todos os revestimentos danifci ados pelas infli trações a reabilitação e substituição de revestimentos nos pavimentos paredes e tetos a reformulação das instalações sanitárias do rés do chão por forma a permitir a sua utilização por pessoas com mobilidade reduzida a reformulação da rede de abastecimento de água e criação de rede predial de combate à incêndios a reformulação da rede de drenagem de águas residuais a reformulação das instalações elétricas iluminção e telecomunicações a execução de infraes trutura para aquecimento ventilação e ar condicionado a instalação de rede de combate a incêndios sistema automático de deteção de incêndio sinalização de emergência e meios de 1a intervenção a instalação e plataforma de escadas interior e a instalação de elevador preservação o edifício fica preservado mantendo a traça exposições a casa dos crivos vai ter mais programação obras deverão estar concluídas em dezembro deste ano josé carlos ferreira
gabriel silva ipn às vezes basta um pequeno gesto para alegrar o coração de quem tem pouco ou nada está aqui um exemplo no seguimento da iniciativa empreendedor 50+ 2025 da região centro promovida pela ccdr centro o instituto pedro nunes enquanto entidade proponente do vencedor da edição deste ano indicou a casa dos pobres para receber uma das componentes do prémio reconhecendo o trabalho meritório desta instituição no apoio diário à comunidade e na promoção da coesão social sugestão que foi aceite pela ccdr centro que irá atribuir o prémio de 1000 euros à casa dos pobres em inícios de setembro dia 8 dir se á que o diga quem assim entender que é um prémio de baixo valor assim pensará quem só vir o lado material das coisas para a casa dos pobres 1000 euros dão sempre muito jeito tapam sempre um buraco e quem sabe se não bastarão para duas colheres de arroz doce como sobremesa numa refeição mais feliz mas com arroz doce ou sem ele o sabor do gesto ninguém lho tira terá sido essa também essa a intenção do presidente do ipn professor gabriel silva que com pouco dinheiro rubricou um lindo gesto que prima pela lembrança e pela elegância margarida mano uma das personalidades mais respeitadas do mundo académico e da vida cívica nacional foi anunciada como candidata a cabeça de lista à assembleia municipal de lisboa pela coligação “por ti lisboa” que une psd cds pp e iniciativa liberal com um percurso académico profssional e político de enorme densidade margarida mano leva à capital um legado de integridade inteligência e dedicação ao serviço público actual vice reitora da universidade católica portuguesa preside à transparência internacional portugal e integra a direcção da ordem dos economistas sublinhando uma vocação que sempre conjugou o rigor técnico com o compromisso ético a sua ligação à academia é longa e reconhecida foi vice reitora da universidade de coimbra onde marcou gerações de estudantes e docentes pelo exemplo de exigência e proximidade em 2015 foi eleita deputada e integrou o segundo governo de pedro passos coelho como ministra da educação e ciência a ligação ao psd surgiu a convite de francisco pinto balsemão fundador do partido que a desafou a transformar a sua “cidadania activa” em participação política hoje regressa ao escrutínio eleitoral como candidata a uma assembleia diferente a municipal de lisboa trazendo consigo a experiência acumulada de várias vidas profssionais e institucionais para carlos moedas actual presidente da câmara municipal de lisboa e candidato a um segundo mandato a escolha de margarida mano de sua iniciativa “reforçará a assembleia municipal como espaço de debate democrático de fscalização activa e de construção de soluções para os desafos da cidade” lisboa recebe com este convite de carlos moedas uma candidata que simboliza a convergência entre saber ética e serviço coimbra empresta assim a lisboa na politica e na universidade católica um dos seus trunfos com a certeza de que servirá lisboa com brilho e coimbra com prestígio maria lúcia amaral o país arde e a liderança do ministério da administração interna esmorece maria lúcia amaral cuja postura já gerava reservas viu a exigência de demissão tornar se pública depois de uma saída abrupta de conferência resumida em um seco “vamos embora” um gesto que parece simbolizar o abandono perante aldeias bombeiros e famílias que veem tudo a arder desde julho portugal contabiliza dois mortos incluindo um bombeiro na covilhã e um ex autarca da guarda enquanto aldeias inteiras explorações rurais e áreas forestais desaparecem entre chamas a coordenação tardia e desorganizada do ministério revelou fragilidades profundas amplifcadas pelo descontentamento crescente de autarcas e operacionais exaustos andré ventura não hesitou exige a demissão imediata e pretende levar o primeiro ministro ao parlamento denunciando omissão incapacidade e ausência de solidariedade do lado socialista josé luís carneiro sugere comissões e medidas institucionais enquanto portugal mantém o estado de alerta e dezenas de ocorrências activas cresce a sensação de que o comando político falhou a cada dia que passa aumenta o risco não apenas das chamas mas de uma crise de confança que ameaça consumir mais do que forestas consome a credibilidade do governo joaquim aires o bombeiro sapador e ciclista solidário natural de lousada está a concluir uma jornada inspiradora que uniu desporto fé e solidariedade no passado dia 12 de agosto partiu da sua terra natal rumo ao vaticano numa travessia de bicicleta com mais de 2 700 quilómetros a favor da associação nacional de esclerose múltipla anem a chegada está prevista para amanhã 29 de agosto na emblemática praça de são pedro em roma local que simboliza não só espiritualidade mas também união e esperança ao longo de 15 etapas intensas joaquim aires não pedalou apenas pela superação pessoal a sua missão maior foi dar visibilidade à esclerose múltipla sensibilizar a sociedade para os desafos diários enfrentados por quem convive com esta doença neurológica crónica e ao mesmo tempo angariar fundos através de uma campanha de crowdfunding activa na plataforma give me pt esta não é a primeira vez que joaquim aires se lança à estrada com o coração ao guidão em 2023 tinha já protagonizado uma viagem até paris da qual resultaram cerca de nove mil euros angariados para instituições de lousada agora o destino é roma e o propósito ainda mais abrangente dar voz a uma causa que muitas vezes permanece invisível a da esclerose múltipla mais do que números ou quilómetros esta iniciativa solidária representa a força de um gesto individual capaz de mobilizar consciências e inspirar acção amanhã quando joaquim aires cruzar a meta simbólica da praça de são pedro não será apenas um ciclista a concluir uma longa viagem será um embaixador da solidariedade levando consigo as vozes de todos aqueles que enfrentam diariamente a esclerose múltipla com coragem e dignidade josé sopas no passado dia 22 de agosto ao completar o seu 97 º aniversário josé rolinho sopas teve a oportunidade de sentir que as relações pessoais quando dimanam de sentimentos verdadeiros irradiam sempre boa luz essa constatação aconteceu num encontro de tertulianos do café brasil na figueira da foz em torno de “uma traição de amigos” gizada por um dos seus membros que nos recintos desportivos fcou conhecido como caldeira nesse encontro feito de simplicidade amizade e sinceridade josé sopas terá sentido no seu íntimo que o cântico dos “parabéns” tinha a sonoridade do “vai d arrinca” que apreendeu e sentiu na prática de desportos náuticos e continuou na preservação da memória do “seu” ginásio não em estilo de armazém mas sim de uma instituição viva mas nem só no ginásio clube figueirense josé sopas deu o melhor de si pois o seu nome fcará para sempre ligado ao nascimento do coral david de sousa ou à colaboração noutras manifestações culturais como o teatro ou os jograis ricardo paiágua é o rosto visível da plataforma “portugal sem chamas” que tem como objectivo ajudar as vítimas dos incêndios apesar de ter sido lançada há pouco tempo a iniciativa já conta com centenas de voluntários que oferecem apoio aos mais diversos níveis nomeadamente bens alojamento transporte roupa alimentos e donativos um auxílio importante numa altura em que tantas pessoas perderam de um momento para o outro aquilo que levaram uma vida para construir esta não é no entanto a primeira vez que ricardo paiágua cria um projecto de carácter solidário também já esteve envolvido nas iniciativas “cama solidária” que durante a pandemia mobilizou centenas de voluntários e caravanas para acolher profssionais de saúde “computador solidário” que permitiu distribuir milhares de computadores a estudantes sem meios para acompanhar as aulas online “acolhe um herói” cujo intuito passou por juntar famílias a bombeiros e operacionais deslocados em grandes incêndios e “acolhe um ucraniano” que mobilizou alojamentos e apoio para centenas de refugiados no início da guerra ricardo paiágua é assim a personifcação daquilo que todos deveríamos ser humanos que se preocupam e que mais do que falar põem em prática joão massano o bastonário da ordem dos advogados anunciou recentemente a criação de uma bolsa de voluntários para ajudar vítimas dos incêndios esta tem como propósito prestar “aconselhamento e apoio jurídico gratuito aos cidadãos e empresas gravemente afectados pelos fogos rurais que têm assolado o país” a ajuda vai desde processos de indemnização a relações com seguradoras e entidades públicas bem como orientação para o acesso a apoios governamentais “entendemos que é nossa responsabilidade profssional e social colocar os recursos jurídicos da advocacia portuguesa ao serviço das comunidades mais necessitadas” sublinhou a ordem a iniciativa não podia ter sido mais bem recebida sendo que já conta com mais de 200 advogados inscritos joão massano garante que nos próximos dias vão ser realizadas as primeiras consultas portugueses preocupam se com o ambiente mas agem pouco a maioria 96% dos portugueses com mais de 45 anos preocupa se com o ambiente mas um terço admite não adoptar comportamentos sustentáveis no dia a dia revela um estudo do cis iscte separar resíduos poupar água e reutilizar sacos estão entre as práticas mais comuns mas ainda insuficientes 42% não separaram lixo na última semana 43% não pouparam água e 38% não reutilizaram sacos os inquiridos apontam como principais obstáculos a falta de transportes públicos eficientes de políticas públicas eficazes e os custos associados “há consciência ambiental mas falta capacidade prática para agir” afirma sandra godinho coordenadora do estudo take action for future generations dificuldades económicas 39% ausência de infra estruturas 33% e falta de informação 18% também são barreiras os temas que mais preocupam são a escassez de água a poluição do ar e o esgotamento de recursos naturais sandra godinho defende mais campanhas dirigidas aos seniores cuja influência nos hábitos familiares é decisiva encontros mágicos regressam a coimbra em setembro com seis dias de ilusão os encontros mágicos regressam a coimbra de 16 a 21 de setembro para a 29 ª edição do maior festival de magia português organizado pela câmara municipal e com direcção artística de luís de matos o evento apresenta seis dias de programação intensa incluindo magia de rua magia na região magia solidária escola de magia e duas galas internacionais estas realizam se a 19 e 20 de setembro no convento são francisco com alguns dos melhores mágicos da actualidade os bilhetes já estão à venda na bilheteira do convento e na ticketline com preços entre 20 e 22 50 euros pessoas com mobilidade reduzida devem adquirir ingressos directamente na bilheteira beneficiando de bilhete gratuito para acompanhante o programa completo será divulgado em breve instituto pedro nunes desafia jovens a pensar a vida no espaço a 11 ª edição da coimbra space summer school csss realiza se em coimbra nos dias 3 4 e 5 de setembro destinada a estudantes investigadores e empreendedores interessados na exploração espacial a escola de verão incentiva a criação de serviços e produtos inovadores que utilizem tecnologia espacial para aplicações terrestres o tema deste ano “habitabilidade no espaço” aborda os desafios da vida fora da terra incluindo saúde física e mental produção de alimentos em órbita e tecnologias de suporte à vida durante três dias os participantes assistem a conferências recebem mentoria de especialistas e convivem com a comunidade espacial portuguesa organizada pelo instituto pedro nunes em parceria com o observatório geofísico e astronómico da uc e o mestrado geoplanet a iniciativa conta com a colaboração das universidades de coimbra nantes e gabriele d annunzio di chieti pescara inscrições até 31 de agosto dgav abre linha de apoio a animais durante incêndios a direcção geral de alimentação e veterinária dgav abriu uma linha telefónica 213 239 621 disponível 24 horas para reportar necessidades de apoio ou acolhimento de animais durante os incêndios através deste contacto é possível sinalizar emergências identifcar carências de alimentação e receber orientações sobre encaminhamentos a medida pretende garantir uma resposta rápida e efcaz sobretudo para agricultores afectados pelos fogos que desde julho têm devastado o norte e centro do país provocando três mortos incluindo um bombeiro vários feridos e danos em habitações e explorações agrícolas portugal activou o mecanismo europeu de protecção civil com dois aviões fire boss em operação e de mais dois canadair até 21 de agosto arderam 234 mil hectares incluindo mais de 50 mil no incêndio de arganil guarda inglesa ganha novo parque urbano para desporto ao ar livre o coimbra cross & fitness parque urbano na margem esquerda do rio mondego na zona da guarda inglesa abriu ao público como novo espaço de prática desportiva ao ar livre com cerca de 17 mil m² o parque integra uma pista de cross e uma zona de cardiofitness destinada a todas as idades e níveis de condição física a pista conta com percursos de 500 e 1 100 metros sinalizados para circulação segura enquanto a zona de cardiofitness dispõe de sete aparelhos para treino muscular e funcional incluindo banco de abdominais barras de flexões e bicicleta dupla o espaço permite corrida caminhada treino de resistência e actividades em grupo oferecendo acesso livre num contexto urbano de fácil fruição o investimento municipal rondou os 10 mil euros com possibilidades futuras de melhorias como plantação de árvores e ponto de água coimbra recebe a 7 ª edição do passeio adaptado “os rodinhas” a 7 de setembro a associação os rodinhas de portugal instituição sem fins lucrativos com sede em coimbra vai realizar no próximo dia 7 de setembro a 7 ª edição do passeio adaptado “os rodinhas” um evento já consolidado no calendário da associação e que pretende promover a inclusão o convívio e a sensibilização para os direitos das pessoas com deficiência o percurso com cerca de 35 quilómetros terá início junto à sede da associação pelas 9h30 e terminará no clube desportivo de assafarge com chegada prevista para as 13h00 até ao momento estão já inscritos 80 participantes entre pessoas com deficiência que se deslocam em cadeiras de rodas com propulsor eléctrico e cidadãos sem qualquer limitação física que os acompanharão de bicicleta no total contando com a logística e a comitiva de apoio estima se que mais de 120 pessoas integrem o evento o programa arranca às 8h00 com a concentração na sede da associação seguindo se o check in e a distribuição do equipamento oficial água e alimentação para o percurso após a partida está agendada uma fotografia de grupo às 10h15 e um reforço alimentar retomando se o passeio às 10h45 a chegada ao clube desportivo de assafarge será seguida de um almoço convívio a organização relembra que o uso de capacete é obrigatório e deixa o convite “traz a tua bicicleta e aceita este desafio ” as inscrições podem ser feitas na página oficial da associação no facebook avança a ampliação do centro de saúde norton de matos a câmara municipal de coimbra aprovou a adjudicação da empreitada de ampliação do centro de saúde norton de matos à empresa conway lda pelo valor de 2 885 447 euros acresce iva à taxa legal em vigor com prazo de execução de 300 dias financiado pelo plano de recuperação e resiliência prr a obra prevê a construção de um novo edifício com dois pisos assistenciais concebido como unidade funcional autónoma com infra estruturas próprias e integração física e funcional no complexo existente a intervenção inclui a requalificação do espaço público envolvente a reorganização viária interna para compatibilizar a circulação com o novo edifício e a criação de 20 lugares de estacionamento tecelagem de almalaguês em exposição na baixa de coimbra a montra do welcome centre do projecto shift coimbra na rua ferreira borges na baixa da cidade acolhe até meados de outubro uma mostra de tecelagem de almalaguês que foi recentemente distinguida com o prémio europeu do património a exposição pretende precisamente assinalar a recente distinção atribuída à candidatura “almalaguês tecendo o amanhã a partir da tapeçaria do tempo” vencedora de um dos prémios europeus do património cultural europa nostra 2025 cofinanciada pelo programa europa criativa da união europeia a iniciativa resulta de uma colaboração entre a câmara municipal de coimbra a associação herança do passado e o bairro comercial digital de coimbra e pretende dar visibilidade ao trabalho desenvolvido na preservação e promoção da tecelagem de almalaguês reconhecida como património cultural imaterial de grande valor histórico e social

In [39]:
print("\n------ CLUSTER 4 ------")
print("\n".join(df_sample[df_sample.cluster_id == 4]["noticia_norm"].head(10)))

------ CLUSTER 4 ------
“estar de banco” hoje é muito mais do que cumprir um turno é sentar se metaforicamente no mesmo banco onde começou a ciência dos nossos hospitais poucos lisboetas imaginam que uma expressão tão corriqueira e viva como “estou de banco” dita por médicos e enfermeiros a anunciar o início do seu turno carrega séculos de história dentro dela é uma dessas heranças silenciosas que atravessam o tempo nascidas nas salas austeras do real hospital de todos os santos onde se misturavam o saber o cheiro dos unguentos e o rumor dos sofredores que enchiam os claustros da cidade nos tempos em que a medicina era ainda mais arte do que ciência o “banco dos médicos” era um lugar físico real de madeira gasta e de trabalho constante era ali que se sentavam os cirurgiões e os físicos do rei debruçados sobre os frascos de vidro translúcido que guardavam amostras de urina as célebres matulas erguidas contra a luz para avaliar cor transparência e espuma o “banco” era a bancada onde se fazia o diagnóstico pela observação direta uma extensão da inteligência e dos sentidos do médico a urina então era o espelho do corpo antes de haver microscópios e reagentes lia se nela o estado da alma e da carne o odor a cor a consistência tudo falava e sim é verdade nos séculos xvii e xviii alguns médicos provavam na com a ponta da língua para confirmar a suspeita de diabetes essa doença que o latim designou mellitus “doce como o mel” no banco provava se a vida com o passar dos séculos o real hospital de todos os santos ardeu no terramoto e no fogo de 1755 mas o seu espírito sobreviveu no hospital de são josé herdeiro direto da sua missão e dos seus costumes a prática transformou se a ciência refinou se mas o vocabulário persistiu continuou se a dizer “estar de banco” para significar o estar de serviço o ocupar o lugar de quem observa cuida e decide o banco deixou de ser uma tábua de madeira e tornou se um símbolo do ofício médico hoje quando um enfermeiro de lisboa ao sair de casa diz “estou de banco” talvez não imagine que repete uma frase nascida entre os ecos do antigo hospital régio carrega consigo sem o saber a memória de séculos de medicina empírica de noites passadas à luz das velas de frascos de vidro sobre o mármore frio de mãos que procuravam compreender o corpo humano através do olhar e por vezes do gosto é assim que as palavras sobrevivem ao tempo mudam de sentido mas guardam o rasto do lugar onde nasceram e “estar de banco” hoje é muito mais do que cumprir um turno é sentar se metaforicamente no mesmo banco onde começou a ciência dos nossos hospitais o banco onde lisboa aprendeu a curar paulo freitas do amaral professor e historiador paulo freitas
foi identificada mais uma morte que possa relacionada com a greve do inem a inspeção geral das atividades em saúde revelou que os atrasos no serviço de emergência influenciaram de forma significativa a morte de um homem em mogadouro bragança em novembro do ano passado declarações de ana paula martins ministra da saúde
hugo ribeiro especialista com competência em dor da equipa comunitária de suporte em cuidados paliativos gaia concluiu em agosto uma missão de voluntariado médico de duas semanas em cabo verde com o objetivo de desenvolver a prática da medicina paliativa no hospital universitário agostinho neto e em todo o pafs a missão resultou de ações de formação realizadas pelo grupo de médicos iniciativa médica 3m e pelo centro de estudos dos cuidados paliativos da faculdade de medicina da universidade de coimbra a missão decorreu nas ilhas de santiago fogo e maio tendo sido um convite do ministério da saude da direção do hospital universitário agostinho neto huan da unidade de cuidados paliativos do fogo e da ordem dos médicos de cabo verde
função pública dos açores terá cerca de 4700 o 0 na reforma até 2030 a função pública dos açores enfrenta uma reforma significativa com cerca de 4 700 trabalhadores a sair até 2030 as saídas obrigam a estratégias de reposição e formação de novos funcionários explica o governo regional filipe torres filipe torres@ acorianoorientalpt até 2030 prevê se a aposentação de cerca de 4 700 funcionários públicos da administração pública regional dos açores num contexto em que a idade média no setor atingiu os 48 75 anos em 2024 os dados foram divulgados pelo governo regional em resposta a um requerimento apresentado pelo ps açores apesar do envelhecimento o número de saídas da função pública açoriana diminuiu nos últimos anos em 2023 deixaram a a administração regional 548 trabalhadores a grande maioria 499 por aposentação no ano seguinte o número desceu para 394 dos quais 339 se reformaram as restantes saídas distribuíram se por caducida de de contrato 12 em 2023 e 30 em 2024 licenças sem vencimento 18 em cada ano e saídas voluntárias que diminuíram de 19 para apenas 7 em dois anos saíram definitivamente 942 trabalhadores a redução global de saídas combinada com novas admissões e realocações contribuiu para o aumento do número total de funcionários públicos que passou de 16 805 no final de 2023 para 17 222 no final de 2024 houve um grande aumento õno número de funcionários que fizeram mobilidade em 2023 391 trabalhadores foram realocados entre serviços e departamentos mas em 2024% o número subiu para 611 o que equivale a um aumento de 56% as mobilidades intercarreiras e intercategorias foram as mais frequentes 210 em 2023 e 304 em 2024 permitindo que trabalhadores assumissem novas funções ou categorias dentro da administração a mobilidade interna entre serviços da própria estrutura regional também aumentou de 107 para 231 casos houve ainda 35 mobi lidades externas saídas parafora da administração regional e 41 cedências por interesse público o número total de funcionários públicos com cargos de nomeação política apresentou uma ligeira baixa depois de atingir 20 815 em 2023 o número recuou para 20 035 em 2024 entre 2021 e 2025 o número de funcionários públicos em cargos de nomeação política aumentou de 51 para 77 um crescimento de 26 funcionários entre os departamentos a vice presidência passou de 8 para 9 cargos a secretaria das finanças de 4 para 7 a educação de 3 para 7 e a saúde de 5 para 7 destacaram se também aumentos expressivos no mar e pescas de 3 para 7 cargos e na juventude habitação e emprego de 4 para 8 a presidência manteve 8 cargos e o am biente e ação climática subiu ligeiramente de 4 para 5 com o objetivo de enfrentar o desafio do envelhecimento dos trabalhadores da função pública o governo regional dos açores criou em novembro de 2024 um grupo de trabalho para o rejuvenescimento da força de trabalho daadministração pública regional apr o organismo tem como missão propor uma estratégia abrangente e de longo prazo centrada na captação de talento jovem na retenção de trabalhadores qualificados e na formação contínua entre as metas definidas estão a análise dos dados demográficos e projeção de necessidades até 2030 a proposta de medidas de rejuvenescimentoe captação de novos profissionais a promoção da formação e desenvolvimento de competências entre os atuais e futuros trabalhadores e a elabora ção de um plano de ação com políticas públicas e ajustamentos legislativos que assegurem uma transição geracional equilibrada ainda segundo o executivo com o objetivo de tornar a função pública mais competitiva houve uma aposta na valorização das carreiras e na mobilidade profissional a progressão remuneratória passou a ser mais previsível permitindo aumentos após a 1obtenção de seis pontos nas avaliações de desempenho e foi eliminado o regime de quotas nas menções qualitativas atribuídas pelo siadapra sistema integrado de gestão e avaliação do desempenho na administração pública regional dos açores administração pública número de aposentações previsto até 2030 exige estratégia de formação e renovação na administração pública regional que no fim de 2024 tinha cerca de 17 mil funcionários pagina 5 17 222 número de funcionários públicos na administração regional no final de 2024 942 número de trabalhadores da função pública que saíram em definitivo entre 2023 e 2024 em 2024 houve 611 trabalhadores que foram realojados um aumento de 56% face ao ano anterior governo regional afirma que cerca de 4 700 trabalhadores da função pública na administração regional vão se aposentar até 2030 filipe torres
o tempo de espera na urgência do hospital amadora sintra está muito acima do recomendado por causa da elevada afluência e da falta de médicos
a nestlé purina através da sua marca pro plan criou uma parceria com a ordem dos médicos veterinários com o objetivo de fortalecer as iniciativas no âmbito da saúde mental destes profissionais

In [10]:
from dotenv import load_dotenv
import os
from openai import OpenAI

# Carregar variáveis do ficheiro .env
load_dotenv()

# Ler a chave a partir do .env
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

dicionario_cluster_para_nome = {}

response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[{"role": "user", "content": "Diz apenas 'Ligação OK'"}]
)

print(response.choices[0].message.content)

Ligação OK

In [11]:
from collections import Counter
import nltk
from nltk.corpus import stopwords
import pandas as pd # Necessário para o .join na extração

# --- PARTE 1: EXTRAÇÃO DE PALAVRAS-CHAVE (TF/IDF SIMPLIFICADO) ---

# Garantir stopwords em português
try:
    nltk.data.find('corpora/stopwords')
except nltk.downloader.DownloadError:
    nltk.download('stopwords')
stop_words = set(stopwords.words('portuguese'))


cluster_palavras = {}

for c in sorted(df_sample["cluster_id"].unique()):
    # Junta todo o texto de um cluster
    palavras = " ".join(df_sample[df_sample.cluster_id == c]["noticia_norm"].astype(str))

    # Tokens filtrados (remove stopwords e pontuação)
    tokens = [
        p.lower()
        for p in palavras.split()
        if p.lower() not in stop_words and len(p) > 2
    ]

    # Guarda as 15 palavras mais comuns
    mais_comuns = [p[0] for p in Counter(tokens).most_common(15)]
    cluster_palavras[c] = mais_comuns

print("✔ Palavras mais frequentes extraídas por cluster.\n")


# --- PARTE 2: ROTULAGEM DOS CLUSTERS (USANDO GPT-4o-mini E 19 FEW-SHOTS) ---

# Lista RÍGIDA das 19 categorias de política pública (A sua taxonomia)
areas_oficiais = """
Agricultura e Floresta; Administração Pública; Ambiente e Clima; Cultura; Defesa;
Desporto; Economia; Educação e Formação; Energia; Habitação; Impostos e taxas;
I&D e Inovação; Justiça; Mar e Pescas; Proteção Social; Saúde; Segurança;
Trabalho; Transportes e Mobilidade
"""

dicionario_cluster_para_nome = {}
# ⚠️ Assume-se que 'client' (OpenAI) está definido e ativo.
print("A rotular os clusters (GPT-4o-mini)...")

# Construção dos 19 exemplos Few-Shot (o prompt extenso)
few_shot_examples = """
Exemplos de Classificação (Obrigatório):

Palavras: hospitais, médicos, SNS, urgências, cuidados de saúde, enfermeiros, vacinação
Categoria: Saúde

Palavras: futebol, campeonato, liga, equipa, golo, estádio, atleta, modalidade, jogos
Categoria: Desporto

Palavras: agricultura, floresta, gado, vinha, produção agrícola, incêndios rurais, campo
Categoria: Agricultura e Floresta

Palavras: tribunais, juiz, advogados, julgamento, processo, procurador, lei, justiça
Categoria: Justiça

Palavras: inflação, investimento, PIB, mercado, exportação, bancos, impostos, finanças, economia
Categoria: Economia

Palavras: câmara municipal, autarquia, serviços públicos, concurso, funcionários, estado
Categoria: Administração Pública

Palavras: clima, aquecimento global, poluição, sustentabilidade, emissões, reciclagem
Categoria: Ambiente e Clima

Palavras: museu, teatro, cinema, artes, património, espetáculo, festival, cultura
Categoria: Cultura

Palavras: defesa nacional, forças armadas, exército, marinha, aeronáutica, missão militar
Categoria: Defesa

Palavras: escola, ensino, alunos, professores, universidade, formação profissional, aulas
Categoria: Educação e Formação

Palavras: energia, petróleo, gás, eletricidade, renovável, solar, eólica, transmissão
Categoria: Energia

Palavras: habitação, renda, imobiliário, arrendamento, casa, obras, construção, crédito
Categoria: Habitação

Palavras: impostos, IVA, IRS, taxas, contribuições, autoridade tributária, fiscal
Categoria: Impostos e taxas

Palavras: investigação, inovação, ciência, startup, tecnologia, laboratório, descoberta
Categoria: I&D e Inovação

Palavras: mar, pescas, oceano, porto, pescadores, costa, navio, recursos marinhos
Categoria: Mar e Pescas

Palavras: segurança social, pensões, reformas, apoios sociais, subsídio, idosos
Categoria: Proteção Social

Palavras: segurança, PSP, GNR, polícia, crime, violência, roubo, investigação, assalto
Categoria: Segurança

Palavras: trabalho, emprego, salário, desemprego, contrato, empresa, horário, sindicato
Categoria: Trabalho

Palavras: transportes, mobilidade, carro, comboio, avião, autocarro, metro, estrada, aeroporto
Categoria: Transportes e Mobilidade
"""

for c, palavras in cluster_palavras.items():

    prompt = f"""
Classifica o seguinte grupo de palavras-chave numa categoria de políticas públicas portuguesas.

Regras de Classificação:
- A resposta TEM de ser UMA das categorias listadas em "Categorias disponíveis".
- Escolhe apenas UMA categoria, a mais representativa.
- Não cries categorias novas.
- Responde APENAS com o nome da categoria.

{few_shot_examples}

Categorias disponíveis:
{areas_oficiais}

Palavras do cluster:
{', '.join(palavras)}

Categoria:
"""
    # ... Resto da chamada API para o GPT (client.chat.completions.create)
    resposta = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}]
    )

    categoria_nome = resposta.choices[0].message.content.strip()
    dicionario_cluster_para_nome[c] = categoria_nome

    print(f"Cluster {c} ➜ {categoria_nome}")

print("\n✔ Nomes de categorias gerados com sucesso!")

✔ Palavras mais frequentes extraídas por cluster.

A rotular os clusters (GPT-4o-mini)...
Cluster 0 ➜ Administração Pública
Cluster 1 ➜ Administração Pública
Cluster 2 ➜ Saúde
Cluster 3 ➜ Economia
Cluster 4 ➜ Habitação
Cluster 5 ➜ I&D e Inovação
Cluster 6 ➜ Administração Pública
Cluster 7 ➜ Administração Pública
Cluster 8 ➜ Administração Pública
Cluster 9 ➜ Administração Pública
Cluster 10 ➜ Trabalho
Cluster 11 ➜ Administração Pública
Cluster 12 ➜ Administração Pública
Cluster 13 ➜ Administração Pública
Cluster 14 ➜ Cultura
Cluster 15 ➜ Economia
Cluster 16 ➜ Administração Pública
Cluster 17 ➜ Economia

✔ Nomes de categorias gerados com sucesso!

In [1]:
import pandas as pd

df_gold = pd.read_csv("../../data_sample/golden_set_10_por_categoria.csv")

In [2]:
# confirmar distribuição
df_gold["Categoria"].value_counts()

Categoria
Saúde                   10
Desporto                10
Agricultura_Floresta    10
Justiça                 10
Economia                10
Admin_Publica           10
Ambiente_Clima          10
Cultura                 10
Defesa                  10
Educação                10
Energia                 10
Habitação               10
Impostos                10
ID_Inovação             10
Mar_Pescas              10
Proteção_Social         10
Segurança               10
Trabalho                10
Transportes             10
Name: count, dtype: int64

In [3]:
df_gold[["Categoria", "id", "titulo"]]

       Categoria         id                                             titulo
0          Saúde  118805777  Médicos não trocam sossego do interior do país...
1          Saúde  119125198  Autoras de ´Uma Aventura´ explicam o SNS aos j...
2          Saúde  119834711  Governo mexe no diploma das urgências regionai...
3          Saúde  118032180  Médicos de Família e a Complementaridade do SN...
4          Saúde  118669104  Índice Saúde Sustentável 2024/25 - Portugueses...
..           ...        ...                                                ...
185  Transportes  119231006  Rail Baltica - Uma nova linha férrea a pensar ...
186  Transportes  117098456  Viseu quer comboio em "velocidade elevada" e "...
187  Transportes  117417867  Mealhada celebra feriado com homenagens - Entr...
188  Transportes  116735331  Penela uma Vila de experiências que pode torna...
189  Transportes  119330614        Habitação e mobilidade no centro do Funchal

[190 rows x 3 columns]