In [2]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\marga\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\marga\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from scikit-learn) (2.3.4)
Requirement already satisfied: scipy>=1.8.0 in c:\users\marga\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\marga\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\marga\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Python313\python.exe -m pip install --upgrade pip

In [9]:
import sklearn

In [11]:
# --- Environment Setup for VS Code ---
import pandas as pd
import numpy as np
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import nltk

# Download NLTK stopwords (only the first time)
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords_pt = stopwords.words('portuguese')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\marga\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

#Sprint 2

In [24]:
# carregar o dataset 

parquet_path = "../../data_sample/cision_news_rows.parquet"

sample = pd.read_parquet(parquet_path, engine="pyarrow")

sample.head()

,id,titulo,noticia,link,data_publicacao,tipo_meio,autores,valor_publicitario,guid,categoria
0,117766326,Novo regime de arrendamento com opção de compr...,O novo regime de arrendamento com opção de com...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,1105.4,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
1,117766609,TRIBUNAL DETECTA OBRAS IRREGULARES EM SANTANA,Tribunal detecta obras irregulares em Santana ...,No link available,2025-06-19 00:00:00+00:00,Imprensa,Miguel Fernandes Luís,1323.1,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
2,117766528,Relatório final da Comissão Parlamentar de Inq...,“Os processos de contratualização subjacente à...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,1097.6,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
3,117766532,Valença prevê concluir em 2026 obras no Centro...,A reabilitação e ampliação do Centro de Saúde ...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,100.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
4,117766576,CHUMBADA MOÇÃO DE REJEIÇÃO DO PCP,Após a votação à moção de rejeição do PCP ao P...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,1445.2,http://pt.cision.com/cp2013/clippingdetails.as...,NaN

In [25]:
sample.head(-100)

,id,titulo,noticia,link,data_publicacao,tipo_meio,autores,valor_publicitario,guid,categoria
0,117766326,Novo regime de arrendamento com opção de compr...,O novo regime de arrendamento com opção de com...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,1105.40,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
1,117766609,TRIBUNAL DETECTA OBRAS IRREGULARES EM SANTANA,Tribunal detecta obras irregulares em Santana ...,No link available,2025-06-19 00:00:00+00:00,Imprensa,Miguel Fernandes Luís,1323.10,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
2,117766528,Relatório final da Comissão Parlamentar de Inq...,“Os processos de contratualização subjacente à...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,1097.60,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
3,117766532,Valença prevê concluir em 2026 obras no Centro...,A reabilitação e ampliação do Centro de Saúde ...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,100.00,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
4,117766576,CHUMBADA MOÇÃO DE REJEIÇÃO DO PCP,Após a votação à moção de rejeição do PCP ao P...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,1445.20,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
...,...,...,...,...,...,...,...,...,...,...
19895,119165457,PS apresentou Rui Miguel Cruz para a presidênc...,O PS apresentou Rui Miguel Cruz como candidato...,https://centralpress.pt/page/107604/redacao/20...,2025-09-16 00:00:00+00:00,Internet,Samuel Guiomar,111.82,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
19896,119165646,Carta aberta une personalidades portuguesas à ...,"Dezenas de portugueses, numa carta aberta, anu...",https://bomdia.eu/carta-aberta-une-personalida...,2025-09-16 00:00:00+00:00,Internet,Fabiana Bravo,600.00,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
19897,119165554,Ventura aponta a Gouveia e Melo com risco e se...,"Tal como parecia inevitável há muito, e foi av...",https://www.dn.pt/pol%C3%ADtica/ventura-aponta...,2025-09-16 00:00:00+00:00,Internet,Leonardo Ralha,16937.38,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
19898,119165563,Governo disponibiliza 30 milhões de euros para...,O Governo vai disponibilizar 30 milhões de eur...,https://odigital.sapo.pt/governo-disponibiliza...,2025-09-16 00:00:00+00:00,Internet,sem autor,272.44,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
19899,119155889,PS apresenta candidatos à Câmara e Juntas de F...,Política PS apresenta candidatos às autárquica...,No link available,2025-09-16 00:00:00+00:00,Imprensa,sem autor,179.50,http://pt.cision.com/cp2013/clippingdetails.as...,NaN

In [26]:
print(sample.shape)
print(sample.columns)
display(sample.head())
display(sample.dtypes)
print(sample.isna().sum())
print("Duplicados por corpo de noticia:", sample.duplicated(subset=["noticia"]).sum()) #mas têm valores unitarios dif

(20000, 10)
Index(['id', 'titulo', 'noticia', 'link', 'data_publicacao', 'tipo_meio',
       'autores', 'valor_publicitario', 'guid', 'categoria'],
      dtype='object')

,id,titulo,noticia,link,data_publicacao,tipo_meio,autores,valor_publicitario,guid,categoria
0,117766326,Novo regime de arrendamento com opção de compr...,O novo regime de arrendamento com opção de com...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,1105.4,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
1,117766609,TRIBUNAL DETECTA OBRAS IRREGULARES EM SANTANA,Tribunal detecta obras irregulares em Santana ...,No link available,2025-06-19 00:00:00+00:00,Imprensa,Miguel Fernandes Luís,1323.1,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
2,117766528,Relatório final da Comissão Parlamentar de Inq...,“Os processos de contratualização subjacente à...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,1097.6,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
3,117766532,Valença prevê concluir em 2026 obras no Centro...,A reabilitação e ampliação do Centro de Saúde ...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,100.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
4,117766576,CHUMBADA MOÇÃO DE REJEIÇÃO DO PCP,Após a votação à moção de rejeição do PCP ao P...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,1445.2,http://pt.cision.com/cp2013/clippingdetails.as...,NaN

id                                  int64
titulo                             object
noticia                            object
link                               object
data_publicacao       datetime64[ns, UTC]
tipo_meio                          object
autores                            object
valor_publicitario                float64
guid                               object
categoria                         float64
dtype: object

id                        0
titulo                    0
noticia                   0
link                      0
data_publicacao           0
tipo_meio                 0
autores                   0
valor_publicitario        0
guid                      0
categoria             20000
dtype: int64
Duplicados por corpo de noticia: 201

só a coluna "categoria" é que tem nulos

In [27]:
# Datas e valores numéricos
sample["data_publicacao"] = pd.to_datetime(sample["data_publicacao"], errors="coerce")
sample["valor_publicitario"] = pd.to_numeric(sample["valor_publicitario"], errors="coerce")

# Normalizar texto das colunas relevantes
def norm_txt(s):
    s = str(s).lower()
    s = re.sub(r"[\:\;\,\.\!\?\(\)\[\]\-\–\—\"\']", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

#vamos ver com o corpo da noticia
sample["noticia"] = sample["noticia"].map(norm_txt)

##TF-IDF (melhor opção de todas)

In [28]:
#4. Vetorização TF-IDF + matriz de similaridade
vectorizer = TfidfVectorizer(stop_words=list(stopwords_pt), ngram_range=(1,2), max_features=20000, min_df=2)
X = vectorizer.fit_transform(sample["noticia"])

# Similaridade (mais baixo aumenta grupos)
S = cosine_similarity(X, dense_output=False)
threshold = 0.76

In [29]:
#5. Agrupamento por similaridade
n = S.shape[0]
visitados = np.zeros(n, dtype=bool)
grupos = []
for i in range(n):
    if visitados[i]:
        continue
    similares = S[i].toarray().ravel() >= threshold
    grupo_idxs = np.where(similares)[0].tolist()
    visitados[grupo_idxs] = True
    grupos.append(grupo_idxs)

grupo_id_map = {idx: gid for gid, g in enumerate(grupos) for idx in g}
sample["grupo_id"] = sample.index.map(grupo_id_map.get).astype("Int64")

In [30]:
# para contagens
from collections import Counter
sizes = Counter(len(g) for g in grupos)
print('Distribuição de tamanhos de grupo:', sizes)
print('Grupos totais:', len(grupos))
print('Grupos com 1 notícia:', sum(1 for g in grupos if len(g)==1))

Distribuição de tamanhos de grupo: Counter({1: 12523, 2: 1579, 3: 413, 4: 185, 5: 107, 6: 62, 7: 35, 10: 26, 8: 18, 9: 17, 12: 10, 13: 8, 14: 7, 17: 6, 19: 6, 11: 6, 20: 6, 15: 4, 16: 3, 23: 3, 25: 3, 18: 2, 26: 1, 31: 1, 27: 1, 24: 1})
Grupos totais: 15033
Grupos com 1 notícia: 12523

In [31]:
# Tabela com número de notícias por grupo
contagem_por_grupo = (
    sample.groupby("grupo_id")
          .size()
          .reset_index(name="num_noticias")
)

# Lista com os ids dos grupos que têm exatamente 32 notícias p.e.
grupos_x = contagem_por_grupo.loc[
    contagem_por_grupo["num_noticias"] == 15, "grupo_id"
].tolist()

print("Grupos com x notícias:", grupos_x)
print("Total de grupos com x notícias:", len(grupos_x))

Grupos com x notícias: [1513, 4556, 4576, 12149]
Total de grupos com x notícias: 4

In [32]:
#6. Escolher o líder por valor publicitário

def lider_valor_publicitario(df, grupo, col_valor="valor_publicitario"):
    # apenas retorna o índice da notícia com maior valor_publicitario dentro do grupo
    idx_validos = [int(i) for i in grupo if 0 <= int(i) < len(df)]
    return int(df.loc[idx_validos, col_valor].idxmax())

lideres = [lider_valor_publicitario(sample, g) for g in grupos]
sample["is_lider"] = False
lideres_validos = [i for i in lideres if i is not None and 0 <= int(i) < len(sample)]
sample.loc[lideres_validos, "is_lider"] = True

In [33]:
sample.head(60)

#aqui da para ver que o 47 e o 26 sao exatamene iguais mas por terem sido publicados a uma hora dif o 47 tem valor € mt superior

,id,titulo,noticia,link,data_publicacao,tipo_meio,autores,valor_publicitario,guid,categoria,grupo_id,is_lider
0,117766326,Novo regime de arrendamento com opção de compr...,o novo regime de arrendamento com opção de com...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,1105.4,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,0,False
1,117766609,TRIBUNAL DETECTA OBRAS IRREGULARES EM SANTANA,tribunal detecta obras irregulares em santana ...,No link available,2025-06-19 00:00:00+00:00,Imprensa,Miguel Fernandes Luís,1323.1,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,1,True
2,117766528,Relatório final da Comissão Parlamentar de Inq...,“os processos de contratualização subjacente à...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,1097.6,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,2,True
3,117766532,Valença prevê concluir em 2026 obras no Centro...,a reabilitação e ampliação do centro de saúde ...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,100.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,3,True
4,117766576,CHUMBADA MOÇÃO DE REJEIÇÃO DO PCP,após a votação à moção de rejeição do pcp ao p...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,1445.2,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,4,True
5,117750707,Investimento superior a 2 milhões de euros - P...,oinstituto politécnico de leiria lançou o conc...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,100.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,5,True
6,117750710,34.º Aniversário da elevação de Pombal a cidad...,perceber como era pombal há 34 anos e ver a ci...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,314.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,6,True
7,117768156,Comissão decide instaurar ação contra Portugal...,curiosidades comissão decide instaurar ação co...,https://terrasdohomem.pt/2025/06/19/comissao-d...,2025-06-19 00:00:00+00:00,Internet,sem autor,102.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,7,True
8,117768279,Investigadores desenvolvem base de dados e mod...,uma equipa de investigadores da faculdade de c...,https://guimaraesagora.pt/investigadores-desen...,2025-06-19 00:00:00+00:00,Internet,sem autor,114.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,8,True
9,117749968,Visita às obras - Requalificação do Parque de ...,o presidente da câmara municipal paulo ferreir...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,100.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,9,True
10,117766145,GOVERNO - Um programa reformista?,o novo governo entregou no fim de semana na as...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,852.6,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,10,True
11,117767742,Faleceu o psiquiatra e escritor Pio Abreu,111 faleceu ontem em coimbra o médico psiquiat...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,178.3,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,11,True
12,117766502,FUNCHAL - Obra do Lar da Santa Casa atinge últ...,a santa casa da misericórdia do funchal assina...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,100.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,12,True
13,117766220,Novo Banco - Americanos do Lone Star lucram ci...,com a venda do novo banco ao grupo francês bpc...,No link available,2025-06-19 00:00:00+00:00,Imprensa,Clara Teixeira,9975.4,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,13,True
14,117766495,Compositor bracarense é finalista do Concurso ...,carlos brito dias compositor e maestro natural...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,144.9,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,14,True
15,117766457,Conselho Económico e Social dos Açores alerta ...,o plenário do conselho económico e social dos ...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,823.2,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,15,True
16,117766456,Protagonista,secretário regional de turismo ambiente e cult...,No link available,2025-06-19 00:00:00+00:00,Imprensa,Eduardo Jesus,171.4,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,16,True
17,117766180,População exige obras na Estrada Nacional 310,camiões cruzam se com dificuldade em via que é...,No link available,2025-06-19 00:00:00+00:00,Imprensa,Rui Dias,5785.5,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,17,True
18,117767754,NERC e câmara trocam acusações,111 a nerc associação empresarial da região de...,No link available,2025-06-19 00:00:00+00:00,Imprensa,Patrícia Cruz Almeida,390.1,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,18,True
19,117766413,EQUIPAMENTO E INFRAESTRUTURAS - Habitação com ...,pedro rodrigues garante que o reforço do parqu...,No link available,2025-06-19 00:00:00+00:00,Imprensa,Marco Milho,614.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,19,True
20,117766407,AGRICULTURA E PESCAS - Orçamento aposta no set...,maciel elencou investimentos que reafri mam o ...,No link available,2025-06-19 00:00:00+00:00,Imprensa,Romina Barreto,514.1,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,20,True
21,117766396,PULSAR ECONÓMICO,70 000 alojamentos locais em risco de ser canc...,No link available,2025-06-19 00:00:00+00:00,Imprensa,Rui Anacleto,271.3,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,21,True
22,117766394,Chumbada moção de rejeição do PCP,luis montenegro disse que “o governo sai do pa...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,309.2,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,22,True
23,117766392,PROGRAMA - Parlamento rejeita moção do PCP ao ...,executivo tem o apoio de 91 deputados 89 do ps...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,514.1,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,4,False
24,117766389,TERRORISMO ONLINE - UE leva Portugal a tribuna...,a comissão europeia vai processar portugal bul...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,142.8,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,23,True
25,117766375,Francisco César exige que a República faça um ...,o deputado do partido socialista eleito pelos ...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,470.4,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,24,True
26,117769207,Detenção de neonazis,a invasão da assembleia da república era apena...,No link available,2025-06-19 06:01:32+00:00,TV,sem autor,4956.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,25,False
27,117768500,Santos Silva continua sem confirmar se vai ent...,augusto santos silva diz que não abdica de qua...,No link available,2025-06-19 06:15:24+00:00,TV,sem autor,502.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,26,True
28,117767443,Portugal começa novo ciclo político,portugal já começou um novo ciclo político o g...,No link available,2025-06-19 06:19:23+00:00,TV,sem autor,7048.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,27,True
29,117767459,Montenegro: Executivo está legitimado pelo Par...,luís montenegro afirma que o executivo está ag...,No link available,2025-06-19 06:19:58+00:00,TV,sem autor,10270.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,28,True
30,117768565,Guerra na Ucrânia,subiu para 28 o número de mortos em kiev na se...,No link available,2025-06-19 06:38:00+00:00,TV,sem autor,1351.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,29,True
31,117767526,Santos Silva continua sem confirmar se vai ent...,augusto santos silva diz que não abdica de qua...,No link available,2025-06-19 06:39:51+00:00,TV,sem autor,12687.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,30,True
32,117767587,Equipa dissolvida em Coimbra,de coimbra vai seguir para a assembleia da rep...,No link available,2025-06-19 06:46:57+00:00,TV,João Bizarro,26179.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,31,True
33,117770123,Programa de Governo,o irs vai baixar a nova redução em 500 milhões...,No link available,2025-06-19 07:25:25+00:00,TV,sem autor,865.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,32,True
34,117768503,Redução do IRS,a nova redução do irs anunciada pelo governo d...,No link available,2025-06-19 07:31:54+00:00,TV,sem autor,431.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,33,False
35,117768050,Sebastião Bugalho em entrevista,a união europeia não pode esperar até 2028 par...,No link available,2025-06-19 08:04:33+00:00,Radio,João Francisco Guerreiro,8464.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,34,True
36,117768653,Detenção de neonazis,o movimento neonazi desmantelado pela judiciár...,No link available,2025-06-19 08:05:25+00:00,Radio,Manuela Barbosa,7590.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,35,True
37,117769396,IRS baixa em setembro com retroativos,o irs deve baixar novamente já em setembro e c...,No link available,2025-06-19 09:01:28+00:00,Radio,sem autor,1819.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,36,True
38,117769495,Alerta de Duarte Pacheco,qualquer pessoa pode entrar e fazer o que quis...,No link available,2025-06-19 09:02:05+00:00,Radio,sem autor,1260.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,37,True
39,117769761,Guerra Israel - Irão: análise,manuel poêjo torres comentador sic analisa as ...,No link available,2025-06-19 10:02:28+00:00,TV,Manuel Poêjo Torres,11087.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,38,True
40,117770309,Juros nos EUA,a reserva federal dos estados unidos manteve a...,No link available,2025-06-19 10:46:36+00:00,TV,sem autor,394.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,39,True
41,117771711,KIPT,o kipt é o laboratório colaborativo na área do...,No link available,2025-06-19 12:14:05+00:00,Radio,Ana Maria Ramos,5147.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,40,True
42,117771724,José Luís Carneiro diz que não vai responder a...,josé luís carneiro afirma que as autárquicas s...,No link available,2025-06-19 12:35:32+00:00,TV,sem autor,2798.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,41,False
43,117771999,"Operação ""Desarme 3D""",pelo menos 3 polícias ou militares estão a ser...,No link available,2025-06-19 13:09:07+00:00,TV,sem autor,357469.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,42,True
44,117772066,Descida do IRS,a descida do irs prevista pelo governo deve se...,No link available,2025-06-19 13:14:50+00:00,TV,André Palma,148567.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,43,True
45,117772108,Juros da casa,os juros da casa desceram em maio pelo 16º mês...,No link available,2025-06-19 13:16:18+00:00,TV,Diana Pinheiro,298822.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,44,True
46,117772420,UE pode mudar direitos aéreos,os passageiros aéreos podem ter menos direitos...,No link available,2025-06-19 13:18:19+00:00,TV,sem autor,559.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,45,True
47,117773094,Detenção de neonazis,a invasão da assembleia da república era apena...,No link available,2025-06-19 13:19:04+00:00,TV,sem autor,21502.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,25,True
48,117772167,"Redução IRS: Governo aprova descida ""nas próxi...",os trabalhadores e os pensionistas deverão rec...,No link available,2025-06-19 13:21:01+00:00,TV,sem autor,104887.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,46,True
49,117772221,José Luís Carneiro diz que não vai responder a...,josé luís carneiro afirma que as autárquicas s...,No link available,2025-06-19 13:24:58+00:00,TV,sem autor,80608.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,41,True
50,117772712,Joaquim Miranda Sarmento fala aos jornalistas,seguir para a reunião do eurogrupo no luxembur...,No link available,2025-06-19 14:02:46+00:00,TV,sem autor,21266.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,47,True
51,117773379,Reunião de ministros das Finanças da zona Euro,o ministro das finanças está no luxemburgo par...,No link available,2025-06-19 14:03:24+00:00,TV,Paulo Dentinho,30752.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,48,True
52,117773193,"""Daqui Moscovo""",daqui moscovo com josé milhazes,No link available,2025-06-19 14:30:21+00:00,TV,José Milhazes,38806.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,49,True
53,117773341,Novas medidas fiscais,a nova redução do irs deverá ser aplicada já e...,No link available,2025-06-19 14:49:43+00:00,TV,sem autor,3466.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,33,True
54,117773749,"Redução IRS: Governo aprova descida ""nas próxi...",miranda sarmento disse ainda que a redução de ...,No link available,2025-06-19 15:31:18+00:00,TV,sem autor,3711.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,50,True
55,117774171,Análise às tensões no Médio Oriente,análise de vasco rosendo editor de economia às...,No link available,2025-06-19 15:53:41+00:00,TV,Vasco Rosendo,8242.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,51,True
56,117774595,"""Operação Desarme 3D"" - Análise",análise está o jornalista do expresso hugo fra...,No link available,2025-06-19 16:36:08+00:00,TV,"Hugo Franco, Francisco Rodrigues",32996.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,52,True
57,117774789,Conflito na Palestina,9 países europeus incluindo portugal pedem que...,No link available,2025-06-19 17:00:20+00:00,TV,sem autor,2796.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,53,True
58,117775088,Paulo Raimundo na Feira do Livro - Direto,o líder do pcp está de visita à feira do livro...,No link available,2025-06-19 17:24:23+00:00,TV,Ana Raquel Leitão,11132.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,54,True
59,117775148,Voo de repatriamento chega esta tarde a Lisboa...,andreia custódio e david freitas estão no aeró...,No link available,2025-06-19 17:47:05+00:00,TV,Andreia Custódio,7980.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN,55,True

In [34]:
#dos 4 grupos que tem 15 noticias
gid = grupos_x[0] #0 é o 1 grupo, 1 o segundo e etc
exemplo_4 = sample.loc[sample["grupo_id"] == gid, ["grupo_id","is_lider","noticia","data_publicacao", "valor_publicitario"]].head(50)
display(exemplo_4)

,grupo_id,is_lider,noticia,data_publicacao,valor_publicitario
1823,1513,False,manifestação a líder parlamentar do livre o se...,2025-06-28 00:00:00+00:00,5927.14
1824,1513,True,durante a manifestação que decorreu entre o ch...,2025-06-28 00:00:00+00:00,44547.31
1827,1513,False,a líder parlamentar do livre o secretário gera...,2025-06-28 00:00:00+00:00,6417.82
1832,1513,False,leonardo negrão manifestantes exigem que o gov...,2025-06-28 00:00:00+00:00,18679.86
1833,1513,False,a líder parlamentar do livre o secretário gera...,2025-06-28 00:00:00+00:00,28767.94
1836,1513,False,a líder parlamentar do livre o secretário gera...,2025-06-28 00:00:00+00:00,43263.40
1847,1513,False,a líder parlamentar do livre o secretário gera...,2025-06-28 00:00:00+00:00,18541.85
1857,1513,False,a manifestação pelo direito à habitação juntou...,2025-06-28 00:00:00+00:00,16324.90
1894,1513,False,livre pcp e bloco acusam governo de agravar cr...,2025-06-28 00:00:00+00:00,418.29
1899,1513,False,casa é direito não luxo voltar às cooperativas...,2025-06-28 00:00:00+00:00,103.18
1900,1513,False,a líder parlamentar do livre o secretário gera...,2025-06-28 00:00:00+00:00,4918.72
1917,1513,False,estas posições foram transmitidas aos jornalis...,2025-06-28 00:00:00+00:00,1500.00
1922,1513,False,lisboa 28 jun 2025 lusa a líder parlamentar do...,2025-06-28 00:00:00+00:00,6757.22
1923,1513,False,a manifestação pelo direito à habitação juntou...,2025-06-28 00:00:00+00:00,4918.72
2313,1513,False,na tarde de sábado várias centenas de pessoas ...,2025-06-29 00:00:00+00:00,5534.02

In [35]:
ver_carac = sample[sample["grupo_id"] == 6042]

display(ver_carac[["is_lider", "noticia", "tipo_meio", "valor_publicitario"]])

,is_lider,noticia,tipo_meio,valor_publicitario
7842,False,a empreitada de reabilitação do teatro clube d...,Internet,148.0
8629,False,foi inaugurada na quinta feira dia 17 de julho...,Internet,108.0
8787,True,com investimento superior a dois milhões e mei...,Imprensa,654.1

In [36]:
# Inspecionar um grupo grande
gid_ex = sample["grupo_id"].value_counts().idxmax()
display(sample[sample["grupo_id"] == gid_ex][["id", "is_lider", "noticia", "valor_publicitario"]].head(50))

,id,is_lider,noticia,valor_publicitario
6241,118161533,False,a presidente da comissão europeia anunciou est...,24699.0
6305,118164410,False,a presidente da comissão europeia anunciou est...,331.0
6308,118165694,False,foto epa política 13 jul 2025 18 55 ue suspend...,24699.0
6314,118165095,False,a presidente da comissão europeia anunciou que...,418.0
6354,118162323,False,i internacional ue suspende medidas retaliação...,218.0
6357,118162272,False,presidente da comissão europeia anunciou que v...,34730.0
6362,118162237,False,a presidente da comissão europeia anunciou hoj...,4281.0
6364,118162142,False,a presidente da comissão europeia anunciou est...,600.0
6366,118162031,False,ursula von der leyen continua a preparar as co...,16826.0
6370,118161791,False,von der leyen argumenta que apesar de manter a...,6949.0
6371,118161765,False,von der leyen diz que a união europeia continu...,2421.0
6373,118162349,False,atualidadeinternacionalue suspende medidas ret...,493.0
6377,118163529,False,a presidente da comissão europeia anunciou hoj...,2249.0
6385,118161649,False,anúncio feito este dominfo pela presidente da ...,322.0
6389,118162949,False,a união europeia continua a preparar as contra...,160.0
6390,118162936,False,a presidente da comissão europeia anunciou hoj...,150.0
6391,118162861,False,d r economiainternacionalue suspende medidas r...,205.0
6392,118162795,False,a presidente da comissão europeia anunciou hoj...,1500.0
6394,118162660,False,anúncio feito este dominfo pela presidente da ...,2676.0
6397,118162579,False,a presidente da comissão europeia anunciou hoj...,6794.0
6402,118161315,True,o presidente dos estados unidos anunciou no sá...,44547.0
6410,118164003,False,rum rádio universitária do minho a presidente ...,123.0
6421,118161455,False,von der leyen anunciou que bruxelas vai suspen...,5000.0
6504,118168013,False,comércio a presidente da comissão europeia anu...,100.0
6509,118168096,False,comércio a presidente da comissão europeia anu...,100.0
6514,118168208,False,comércio a presidente da comissão europeia anu...,100.0
6516,118167841,False,111 a presidente da comissão europeia anunciou...,133.7
6533,118167922,False,a presidente da comissão europeia anunciou est...,414.1
6536,118168337,False,comércio a presidente da comissão europeia anu...,100.0
6824,118233559,False,ue suspende medidas retaliação contra eua para...,142.5

## SBERT + kmeans (uma das opcões que testámos)

In [39]:

from sentence_transformers import SentenceTransformer
from sklearn.cluster import MiniBatchKMeans

c:\Users\marga\Downloads\Planapp-main (1)\Planapp-main\Planapp\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [40]:
parquet_path = "../../data_sample/cision_news_rows.parquet"
sample = pd.read_parquet(parquet_path, engine="pyarrow")

# Usa só o corpo da notícia
sample["noticia"] = sample["noticia"].astype(str).fillna("")

print(f" Dataset carregado com {len(sample)} linhas e {len(sample.columns)} colunas.")
sample.head()

 Dataset carregado com 20000 linhas e 10 colunas.

,id,titulo,noticia,link,data_publicacao,tipo_meio,autores,valor_publicitario,guid,categoria
0,117766326,Novo regime de arrendamento com opção de compr...,O novo regime de arrendamento com opção de com...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,1105.4,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
1,117766609,TRIBUNAL DETECTA OBRAS IRREGULARES EM SANTANA,Tribunal detecta obras irregulares em Santana ...,No link available,2025-06-19 00:00:00+00:00,Imprensa,Miguel Fernandes Luís,1323.1,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
2,117766528,Relatório final da Comissão Parlamentar de Inq...,“Os processos de contratualização subjacente à...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,1097.6,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
3,117766532,Valença prevê concluir em 2026 obras no Centro...,A reabilitação e ampliação do Centro de Saúde ...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,100.0,http://pt.cision.com/cp2013/clippingdetails.as...,NaN
4,117766576,CHUMBADA MOÇÃO DE REJEIÇÃO DO PCP,Após a votação à moção de rejeição do PCP ao P...,No link available,2025-06-19 00:00:00+00:00,Imprensa,sem autor,1445.2,http://pt.cision.com/cp2013/clippingdetails.as...,NaN

In [18]:
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

# Pode demorar alguns minutos para 20k textos!
embeddings = model.encode(sample["noticia"].tolist(), batch_size=64, show_progress_bar=True)

c:\Users\inesc\Downloads\ISCTE\Planapp\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\inesc\.cache\huggingface\hub\models--sentence-transformers--paraphrase-multilingual-MiniLM-L12-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Batches: 100%|██████████| 313/313 [18:33<00:00,  3.56s/it]

In [19]:
from sklearn.cluster import MiniBatchKMeans
from sklearn.metrics import silhouette_score

# Lista dos valores de clusters que queres testar
cluster_tests = [200, 500, 700, 1000]

# Dicionário para guardar os resultados
silhouette_scores = {}

for n_clusters in cluster_tests:
    print(f"\n===== Testando n_clusters = {n_clusters} =====")
    kmeans = MiniBatchKMeans(n_clusters=n_clusters, random_state=42, batch_size=256, max_iter=500)
    labels = kmeans.fit_predict(embeddings)
    score = silhouette_score(embeddings, labels)
    silhouette_scores[n_clusters] = score
    print(f"Silhouette Score: {score:.3f}")

    # Guarda clusters no DataFrame para poderes explorar depois
    sample[f"cluster_{n_clusters}"] = labels

    # Exemplo: distribuições dos tamanhos de cluster
    print("Distribuição dos tamanhos:", pd.Series(labels).value_counts().head(10).to_dict())

===== Testando n_clusters = 200 =====
Silhouette Score: -0.028
Distribuição dos tamanhos: {76: 702, 99: 539, 6: 409, 161: 403, 119: 376, 53: 363, 26: 358, 159: 337, 33: 301, 49: 289}

===== Testando n_clusters = 500 =====
Silhouette Score: -0.032
Distribuição dos tamanhos: {63: 360, 7: 330, 182: 289, 125: 268, 378: 238, 85: 234, 370: 226, 453: 218, 316: 207, 74: 205}

===== Testando n_clusters = 700 =====
Silhouette Score: -0.042
Distribuição dos tamanhos: {448: 286, 534: 264, 453: 251, 29: 224, 385: 219, 139: 216, 446: 212, 7: 203, 170: 203, 655: 200}

===== Testando n_clusters = 1000 =====
Silhouette Score: -0.037
Distribuição dos tamanhos: {217: 253, 26: 250, 708: 238, 787: 229, 394: 216, 317: 198, 95: 179, 460: 163, 296: 162, 442: 153}

In [20]:
cluster_n = 1000

# Ver quantidades por grupo
print(sample[f"cluster_{cluster_n}"].value_counts().sort_values(ascending=False).head(10))

# Ver detalhes de um cluster específico (ex: 5)
g = 5
display(sample[sample[f"cluster_{cluster_n}"] == g][["id", "noticia"]].head(10))

# Ver o líder por valor publicitário em cada cluster escolhido
sample["valor_publicitario"] = pd.to_numeric(sample["valor_publicitario"], errors="coerce")
sample["is_lider"] = (
    sample.groupby(f"cluster_{cluster_n}")["valor_publicitario"]
    .transform(lambda x: x == x.max())
)
display(sample[sample["is_lider"]][[f"cluster_{cluster_n}", "id", "noticia", "valor_publicitario"]].head(10))

cluster_1000
217    253
26     250
708    238
787    229
394    216
317    198
95     179
460    163
296    162
442    153
Name: count, dtype: int64

              id                                            noticia
17277  119007270  Trump garantiu que se a União Europeia (UE) nã...
17303  119006859  Trump garantiu que se a União Europeia (UE) nã...
17314  119007097  "A Europa atacou hoje uma outra grande empresa...
17467  119006577  "A Europa atacou hoje uma outra grande empresa...

,cluster_1000,id,noticia,valor_publicitario
31,88,117767526,Augusto Santos Silva diz que não abdica de qua...,12687.0
32,229,117767587,De Coimbra vai seguir para a Assembleia da Rep...,26179.0
45,23,117772108,Os juros da casa desceram em maio pelo 16º mês...,298822.0
51,968,117773379,O ministro das Finanças está no Luxemburgo par...,30752.0
80,898,117776710,"O ministro das Finanças, Joaquim Miranda Sarme...",477761.0
82,140,117776742,Gouveia e Melo criticou os últimos Governos pe...,399216.0
83,297,117776871,Esquerda/Direita com Luís Campos Ferreira e Eu...,395472.0
102,311,117804062,"Sangue, sémen e fezes transmitem micro-organis...",5534.0
116,997,117844375,EXPECTATIVA SOBRE A DECISÃO da localização do ...,309.1
152,465,117798916,Os governos de França e Itália defenderam que ...,28768.0